baseURL = "http://example.org/"
languageCode = "en-us"
title = "I losted I."
theme = "minimal"

[params]
    author = "Ainashi / …FGH_JKL…"
    description = "しがないボカロPのブログです。"
    githubUserName = "h-j-ainashi"
    accent = "red"
    showBorder = true
    font = "Raleway"
    highlight = true
    highlightStyle = "dark"

[[menu.main]]
    url = "/guidelines/"
    name = "各種ガイドライン"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "制作物についての記事"
    weight = 2

[[menu.main]]
    url = "mailto:ainashi.music@gmail.com"
    name = "ご連絡"
    weight = 3

[[menu.icon]]
    url = "https://marshmallow-qa.com/h_j_ainashi"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/h-j-ainashi"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://www.youtube.com/channel/UCEyCwi44UxQ5O_wkx9aZO1w"
    name = "fab fa-youtube"
    weight = 3

