baseURL = "https://h-j-ainashi.github.io"
languageCode = "ja-jp"
title = "I losted I. - Ainashi Official"
theme = "SimpleIntro"

[params] 
    mainbg = "https://h-j-ainashi.github.io/images/top-bg.jpg"
    name = "Ainashi / …FGH_JKL…"
    mainTitle = "アイをなくした。 / I losted I."
    mainText = "アイをなくしました。よこせください。"

[menus]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "#about"
