baseURL = "https://h-j-ainashi.github.io"
languageCode = "ja-jp"
title = "I losted I."
theme = "minimal"
publishDir = "docs"

[params]
    author = "Ainashi / …FGH_JKL…"
    description = "アイなし、しがないボカロPです。"
    githubUserName = "h-j-ainashi"
    accent = "red"
    backgroundColor = "#fff0f0"
    textColor = "#ffffff"
    showBorder = true
    font = "Raleway"
    highlight = true
    highlightStyle = "dark"
    css = [
        "css/add.css"
    ]

[[menu.main]]
    url = "/"
    name = "トップ"
    weight = 1

[[menu.main]]
    url = "/guidelines/"
    name = "各種ガイドライン"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "制作物についての記事"
    weight = 3

[[menu.main]]
    url = "mailto:ainashi.music@gmail.com"
    name = "ご連絡"
    weight = 4

[[menu.main]]
    url = "/links/"
    name = "リンク集"
    weight = 5

[[menu.icon]]
    url = "https://marshmallow-qa.com/h_j_ainashi"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/h-j-ainashi"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://www.youtube.com/channel/UCEyCwi44UxQ5O_wkx9aZO1w"
    name = "fab fa-youtube"
    weight = 3

[[menu.icon]]
    url = "https://twitter.com/h_j_ainashi"
    name = "fab fa-twitter"
    weight = 4
