baseURL = "https://h-j-ainashi.github.io"
languageCode = "ja-jp"
title = "I losted I."
theme = "minimal"
publishDir = "docs"
description = "I losted I. / アイなし、ただのしがないボカロPのもの書き部屋です。"

[permarinks]
    music = "/post/music/:filename/"

[params]
    author = "Ainashi / …FGH_JKL…"
    description = "アイなし、ただのしがないボカロPです。"
    githubUserName = "h-j-ainashi"
    accent = "red"
    backgroundColor = "#fff0f0"
    textColor = "#ffffff"
    showBorder = false
    font = ""
    highlight = true
    highlightStyle = "dark"
    favicon = "img/icon.png"
    CustomCss = "css/add.css"
    LatestCssDate = "20210418"

[[menu.main]]
    url = "/"
    name = "アイをなくした。"
    weight = 1

[[menu.main]]
    url = "/guidelines/"
    name = "各種DL&ガイドライン"
    weight = 2
[[menu.main]]
    url = "/events/"
    name = "開催中のイベント"
    weight = 3

[[menu.main]]
    url = "/tags/"
    name = "制作物についての記事"
    weight = 4

[[menu.icon]]
    url = "/links/"
    name = "fas fa-link"
    weight = 1

[[menu.icon]]
    url = "https://docs.google.com/forms/d/e/1FAIpQLScVwx2drmwjJoYvarJ7A6_kbBCtpWd0w0UIFURhQcbnOhrZ2A/viewform?usp=sf_link"
    name = "fas fa-envelope"
    weight = 2

[[menu.icon]]
    url = "https://marshmallow-qa.com/h_j_ainashi?utm_medium=url_text&utm_source=promotion"
    name = "fas fa-heart"
    weight = 3

[[menu.icon]]
    url = "https://github.com/h-j-ainashi"
    name = "fab fa-github"
    weight = 4

[[menu.icon]]
    url = "https://www.youtube.com/channel/UCEyCwi44UxQ5O_wkx9aZO1w"
    name = "fab fa-youtube"
    weight = 5

[[menu.icon]]
    url = "https://twitter.com/h_j_ainashi"
    name = "fab fa-twitter"
    weight = 6
